---
version: "2.1"
services:
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Toronto
            - UMASK_SET=022 #optional
        volumes:
            - /mnt/md0/public/Videos/TV:/tv
            - /mnt/md0/docker/AppData:/config
            - /mnt/md0/public/Downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped