---
version: "2"
services:
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Toronto
            - UMASK_SET=022
            - WEBUI_PORT=8080
        volumes:
            - /mnt/md0/docker/AppData:/config
            - /mnt/md0/public/Downloads:/downloads
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
        restart: unless-stopped